c  -*- Fortran -*-
      write(*,*) '****************************************************************************'
      write(*,*) '***                                                                      ***'
      write(*,*) '***             '//achar(27)//'[1;31m********************************************'//achar(27)//'[0m'//'             ***'
      write(*,*) '***             '//achar(27)//'[1;31m*   bbH 4FS -- yt^2 component (HEFT)       *'//achar(27)//'[0m'//'             ***'
      write(*,*) '***             '//achar(27)//'[1;31m*   NLO QCD + PS, amplitudes from Recola2  *'//achar(27)//'[0m'//'             ***'
      write(*,*) '***             '//achar(27)//'[1;31m********************************************'//achar(27)//'[0m'//'             ***'
      write(*,*) '***                                                                      ***'
      write(*,*) '*** '//achar(27)//'[1;31m If you use this program for scientific work, please cite: '//achar(27)//'[0m'//'          ***'
      write(*,*) '***                                                                      ***'
      write(*,*) '*** '//achar(27)//'[1;31m For the yt^2 contribution to bbH at NLO+PS:'//achar(27)//'[0m'//'                        ***'
      write(*,*) '*** '//achar(27)//'[1;31m S. Manzoni, E. Mazzeo, J. Mazzitelli, M. Wiesemann, M. Zaro'//achar(27)//'[0m'//'        ***'
      write(*,*) '*** '//achar(27)//'[1;31m (arXiv:2307.09992)                                        '//achar(27)//'[0m'//'         ***'
      write(*,*) '***                                                                      ***'
      write(*,*) '*** '//achar(27)//'[1;31m For the top-Yukawa contributions to bbH (exact mt at LO):'//achar(27)//'[0m'//'          ***'
      write(*,*) '*** '//achar(27)//'[1;31m N. Deutschmann, F. Maltoni, M. Wiesemann, M. Zaro'//achar(27)//'[0m'//'                  ***'
      write(*,*) '*** '//achar(27)//'[1;31m (arXiv:1808.01660)                                        '//achar(27)//'[0m'//'         ***'
      write(*,*) '***                                                                      ***'
      write(*,*) '*** '//achar(27)//'[1;31m For the one-loop amplitudes (Recola2):'//achar(27)//'[0m'//'                             ***'
      write(*,*) '*** '//achar(27)//'[1;31m A. Denner, J.-N. Lang, S. Uccirati, CPC 224(2018)346'//achar(27)//'[0m'//'               ***'
      write(*,*) '*** '//achar(27)//'[1;31m (arXiv:1711.07388)                                        '//achar(27)//'[0m'//'         ***'
      write(*,*) '*** '//achar(27)//'[1;31m For the tensor integrals (Collier):'//achar(27)//'[0m'//'                                ***'
      write(*,*) '*** '//achar(27)//'[1;31m A. Denner, S. Dittmaier, L. Hofer, CPC 212(2017)220'//achar(27)//'[0m'//'                ***'
      write(*,*) '*** '//achar(27)//'[1;31m (arXiv:1604.06792)                                        '//achar(27)//'[0m'//'         ***'
      write(*,*) '***                                                                      ***'
      write(*,*) '*** '//achar(27)//'[1;31m For the POWHEG BOX RES framework:'//achar(27)//'[0m'//'                                  ***'
      write(*,*) '*** '//achar(27)//'[1;31m T. Jezo, P. Nason (arXiv:1509.09071)'//achar(27)//'[0m'//'                               ***'
      write(*,*) '***                                                                      ***'
      write(*,*) '****************************************************************************'
      write(*,*) '****************************************************************************'
